### ISSUE TITLE
example with future and parallel CV?

### ISSUE THREAD

**Issue by osofr** [jeremyrcoyle/origami#17]
Is it possible to provide a quick working example for parallel CV evaluation using future back-end? 

Presumably, parallel CV is working? If its not implemented yet, I am happy to close this issue, thanks so much!

**Comment by jeremyrcoyle** [comment]
Aside from the other issue you opened (https://github.com/jeremyrcoyle/origami/issues/16), it's working. We've been pointing people to Henrik's `future` documentation here: https://github.com/HenrikBengtsson/future , as parallelizing `origami` is now just a matter of specifying a future `plan`. @ck37 also requested a parallel example though, so maybe it's worth having a minimal one, just so people can get a sense of how it works before reading more in depth about Henrik's package. @nhejazi, can you adapt the code here: https://github.com/jeremyrcoyle/origami/blob/master/tests/testthat/test_future_plan.R into an example? At some point, it might also be worth demonstrating that `cv_fun`s themselves can create futures, and therefore we can do nested parallelization as in this example: https://github.com/HenrikBengtsson/future#nested-futures-and-evaluation-topologies This will be the mechanism by which the new `origami_Superlearner` parallelizes across folds and learners.

**Comment by osofr** [comment]
Great, thanks a lot!

Just to clarify, any time I use future lapply in nested loops, the
parallelization will be automated and balanced across several nested
layers? Will look at your links, thanks!

**Comment by nhejazi** [comment]
@jeremyrcoyle - The test has been modified (with practically minimal changes) as an example in the `cross_validate` function [here](https://github.com/jeremyrcoyle/origami/blob/master/inst/examples/cv_parallel_example.R) as of cf2407a.
