### ISSUE TITLE
Added-value of origami compared to existing packages?

### ISSUE THREAD

**Issue by pat-s** [jeremyrcoyle/origami#18]
Hi there, 

I have just been made aware of your package [here](https://github.com/mlr-org/mlr/pull/1891#issuecomment-314899929). 

I am the maintainer of another CV framework ([sperrorest](https://github.com/pat-s/sperrorest)) with a lot of partitioning methods (see all the [partitioning methods here](https://pat-s.github.io/sperrorest/reference/index.html)).

I am about to deprecate my package and integrate all partition functions into [mlr](https://github.com/mlr-org/mlr) because it is a much bigger framework providing all kind of possibilities when it comes to learning, error erstimation, tuning etc and it provides a good [documentation](https://mlr-org.github.io/mlr-tutorial/devel/html/index.html). 

I would like to ask

1. are you aware of packages like `mlr` or `caret` (I guess you are)
2. what are the benefits of `origami`?

Please do not be offended by this issue; I am really curious about your motivation and reasons as both our packages seem to be somewhat similar.

**Comment by nhejazi** [comment]
Hello Pat ---

Thanks for reaching out about our `origami` package. We're very glad to hear that others are already aware of it, given how recently we completed this package.

I certainly wasn't aware of your `sperrorest` package, but having looked at it rather quickly, it seems like quite a cool idea!

In regard to your questions: We're certainly aware of larger frameworks like `mlr` and `caret`, though both of these are targeted specifically towards various machine learning tasks -- in contrast, `origami` is meant to provide a generalized framework for cross-validation, wherein various schemes for cross-validation (both simple schemes like v-fold and more advanced ones like those for time series) can be implemented and subsequently applied directly to most any R function that the user specifies. For a very simple example, you might see the `cvlm` function in the package vignette [here](http://nimahejazi.org/origami/articles/generalizedCV.html). `origami` also provides facilities for easy parallelization on most environments via the [`future`](https://github.com/HenrikBengtsson/future) package.

We hope that `origami` will grow to be adopted as a backend for most cross-validation needs already used in larger machine learning frameworks, though it can certainly be used on its own for simple functions (as in the case of `cvlm`). To that end, we are already in the process of integrating `origami` with [`SuperLearner`](https://github.com/jeremyrcoyle/SuperLearner), the ensemble learning algorithm developed by our group.

Hope this answers your inquiry somewhat! @jeremyrcoyle will be able to comment in further detail if I've missed anything.

**Comment by pat-s** [comment]
Thanks for the quick reply! 

If `origami` is implemented in a bigger framework like `SuperLearner` than I understand the motivation :) Thats basically the same I am doing now just with `mlr`.  

I also use the `future` package within `sperrorest` and maybe it will also be used in `mlr` someday. Let's see 👍 

Keep up the good work, it looks like this after having a first look on your package 👍
