### ISSUE TITLE
DOI Issues

### ISSUE THREAD

**Issue by wrathematics** [jeremyrcoyle/origami#25]
The [DOI](https://zenodo.org/record/835603) listed for the package references package version 1.0 instead of 0.8.0 and links to the wrong release tag under "related identifiers". Additionally, there is a fourth author listed under the DOI who is not listed in the package DESCRIPTION (Cheng; Chris Kennedy).

**Comment by nhejazi** [comment]
Thanks for pointing out this inconsistency. The issue has been corrected by minting a new DOI with Zenodo, now linked from the corresponding badge in the `README.md`.
